name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      #- run: |
      #    sudo apt update && sudo apt install -y build-essential gcc-multilib gcc-mingw-w64 binutils-mingw-w64
      - uses: cli/gh-extension-precompile@v2
        with:
          build_script_override: "./build.sh"
          go_version: "1.23.4"
        #env:
          #  CGO_ENABLED: 1

  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update && sudo apt install -y g++-arm-linux-gnueabihf build-essential
      - uses: cli/gh-extension-precompile@v2
        with:
          build_script_override: "./build.sh"
          go_version: "1.23.4"
        env:
          CGO_ENABLED: 1
